[base]
data_dir_path = "/Users/suoyuan/work/project/rust/starcoin_stargate/sgterraform/sgchain/dev/val/1"
node_sync_retries = 7
node_sync_channel_buffer_size = 10
node_async_log_chan_size = 256

[metrics]
dir = "metrics"
collection_interval_ms = 1000
push_server_addr = ""

[execution]
address = "localhost"
port = 60788
testnet_genesis = false
genesis_file_location = "genesis.blob"

[admission_control]
address = "::1"
admission_control_service_port = 60776
need_to_check_mempool_before_validation = false
max_concurrent_inbound_syncs = 100

[admission_control.upstream_proxy_timeout]
secs = 1
nanos = 0

[debug_interface]
admission_control_node_debug_port = 60778
secret_service_node_debug_port = 60784
storage_node_debug_port = 60786
metrics_server_port = 60780
public_metrics_server_port = 60782
address = "::1"

[storage]
address = "localhost"
port = 60794
dir = "libradb/db"
grpc_max_receive_len = 100000000

[[networks]]
peer_id = "8deeeaed65f0cd7484a9e4e5ac51fbac548f2f71299a05e000156031ca78fb9f"
listen_address = "/ip4/{CHAIN_IP}/tcp/60750"
advertised_address = "/ip4/{CHAIN_IP}/tcp/60750"
discovery_interval_ms = 1000
connectivity_check_interval_ms = 5000
enable_encryption_and_authentication = false
is_permissioned = false
role = "validator"
network_keypairs_file = "8deeeaed65f0cd7484a9e4e5ac51fbac548f2f71299a05e000156031ca78fb9f.node.network.keys.toml"
network_peers_file = "8deeeaed65f0cd7484a9e4e5ac51fbac548f2f71299a05e000156031ca78fb9f.network_peers.config.toml"
seed_peers_file = "8deeeaed65f0cd7484a9e4e5ac51fbac548f2f71299a05e000156031ca78fb9f.seed_peers.config.toml"
is_public_network = true

[consensus]
max_block_size = 100
proposer_type = "multiple_ordered_proposers"
contiguous_rounds = 2
consensus_keypair_file = "8deeeaed65f0cd7484a9e4e5ac51fbac548f2f71299a05e000156031ca78fb9f.node.consensus.keys.toml"
consensus_peers_file = "consensus_peers.config.toml"
consensus_type = "pow"

[mempool]
broadcast_transactions = true
shared_mempool_tick_interval_ms = 50
shared_mempool_batch_size = 100
shared_mempool_max_concurrent_inbound_syncs = 100
capacity = 1000000
capacity_per_user = 100
system_transaction_timeout_secs = 86400
system_transaction_gc_interval_ms = 180000
mempool_service_port = 60790
address = "localhost"

[state_sync]
chunk_limit = 1000
tick_interval_ms = 100
long_poll_timeout_ms = 30000
max_chunk_limit = 1000
max_timeout_ms = 120000
upstream_peers = []

[log_collector]
is_async = true
[vm_config.publishing_options]
type = "Open"

[vm_config.mode]
type = "Onchain"

[secret_service]
address = "localhost"
secret_service_port = 60792
