[base]
data_dir_path = "/opt/starcoin"
node_sync_retries = 7
node_sync_channel_buffer_size = 10
node_async_log_chan_size = 256

[metrics]
dir = "metrics"
collection_interval_ms = 1000
push_server_addr = ""

[execution]
address = "localhost"
port = 60768
testnet_genesis = false
genesis_file_location = "genesis.blob"

[admission_control]
address = "::1"
admission_control_service_port = 60756
need_to_check_mempool_before_validation = false
max_concurrent_inbound_syncs = 100

[admission_control.upstream_proxy_timeout]
secs = 1
nanos = 0

[debug_interface]
admission_control_node_debug_port = 60758
secret_service_node_debug_port = 60764
storage_node_debug_port = 60766
metrics_server_port = 60760
public_metrics_server_port = 60762
address = "::1"

[storage]
address = "localhost"
port = 60774
dir = "libradb/db"
grpc_max_receive_len = 100000000

[[networks]]
peer_id = "1e5d5a74b0fd09f601ac0fca2fe7d213704e02e51943d18cf25a546b8416e9e1"
listen_address = "/ip4/{CHAIN_IP}/tcp/60750"
advertised_address = "/ip4/{CHAIN_IP}/tcp/60750"
discovery_interval_ms = 1000
connectivity_check_interval_ms = 5000
enable_encryption_and_authentication = false
is_permissioned = false
role = "validator"
network_keypairs_file = "1e5d5a74b0fd09f601ac0fca2fe7d213704e02e51943d18cf25a546b8416e9e1.node.network.keys.toml"
network_peers_file = "1e5d5a74b0fd09f601ac0fca2fe7d213704e02e51943d18cf25a546b8416e9e1.network_peers.config.toml"
seed_peers_file = "1e5d5a74b0fd09f601ac0fca2fe7d213704e02e51943d18cf25a546b8416e9e1.seed_peers.config.toml"
is_public_network = true

[consensus]
max_block_size = 100
proposer_type = "multiple_ordered_proposers"
contiguous_rounds = 2
consensus_keypair_file = "1e5d5a74b0fd09f601ac0fca2fe7d213704e02e51943d18cf25a546b8416e9e1.node.consensus.keys.toml"
consensus_peers_file = "consensus_peers.config.toml"
consensus_type = "p_o_w"

[mempool]
broadcast_transactions = true
shared_mempool_tick_interval_ms = 50
shared_mempool_batch_size = 100
shared_mempool_max_concurrent_inbound_syncs = 100
capacity = 1000000
capacity_per_user = 100
system_transaction_timeout_secs = 86400
system_transaction_gc_interval_ms = 180000
mempool_service_port = 60770
address = "localhost"

[state_sync]
chunk_limit = 1000
tick_interval_ms = 100
long_poll_timeout_ms = 30000
max_chunk_limit = 1000
max_timeout_ms = 120000
upstream_peers = []

[log_collector]
is_async = true
[vm_config.publishing_options]
type = "Open"

[vm_config.mode]
type = "Onchain"

[secret_service]
address = "localhost"
secret_service_port = 60772
